In [35]:
# vektor python numpy with range value
import numpy as np
print("vektor default python\n")
a = np.arange(1,20,1)
b = np.arange(1,20,2)

import numpy as np
print (" \n vektor via numpy \n")

# vektor via numpy
c = np.array ([1,2,3,4,5])
d = np.array ([1.5, 2.5, 5, 6, 7])

print(a)
print(b)
print(a.ndim)
print(a.shape)

vektor default python

 
 vektor via numpy 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
1
(19,)


In [36]:
# mengubah dari 1D menjadi matrik 2D
a = np.arange(1,21,1)
c = a.reshape((4,5))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [37]:
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
list4 = ["abc", 34, True, 40, "male"]

print(list1);

#a. menggabungkan
list5 = list1 + list2
print(list5)

#b. mengambil nilai
print(list1[1])

#c. menyisipkan
list1.insert(1, True)
list1.append(10)
list1.extend([100, 200, 300])
print(list1)

#d. menghapus
list1.remove(True)
list1.pop(1)
del list1[0]
print(list1)

#e. mengurutkan isi
list2.sort()
print(list2)
list2.sort(reverse = True)
print(list2)
list6 = sorted(list2)
print(list6)


['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry', 1, 5, 7, 9, 3]
banana
['apple', True, 'banana', 'cherry', 10, 100, 200, 300]
['cherry', 10, 100, 200, 300]
[1, 3, 5, 7, 9]
[9, 7, 5, 3, 1]
[1, 3, 5, 7, 9]


In [38]:
#data frame
import pandas as pd
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),columns=['a', 'b', 'c'])

print(df,"\n")

print(df['a'],"\n")
print(df[['a']],"\n")
print(df[['a', 'c']],"\n")
print(df.sum(),"\n")
print(df.mean(),"\n")
print(df.max(),"\n")
print(df.min(),"\n")

df['d'] = df['a'] + df['b'] + df['c']
print(df,"\n")

df['mean'] = df[['a', 'b', 'c', 'd']].mean(axis=1)
print(df,"\n")

hasil = df[(df['a'] > 3) & (df['c'] > 6)]
print(hasil)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9 

0    1
1    4
2    7
Name: a, dtype: int64 

   a
0  1
1  4
2  7 

   a  c
0  1  3
1  4  6
2  7  9 

a    12
b    15
c    18
dtype: int64 

a    4.0
b    5.0
c    6.0
dtype: float64 

a    7
b    8
c    9
dtype: int64 

a    1
b    2
c    3
dtype: int64 

   a  b  c   d
0  1  2  3   6
1  4  5  6  15
2  7  8  9  24 

   a  b  c   d  mean
0  1  2  3   6   3.0
1  4  5  6  15   7.5
2  7  8  9  24  12.0 

   a  b  c   d  mean
2  7  8  9  24  12.0
